language: bash

branches:
  only:
  - master

services:
  - docker

before_install:
  - docker build -t pos_ver_api POS_version_API

script:
  - docker run -it -d --rm pos_ver_api /bin/sh -c "flask --version"

